name: crypto_v1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+2
  dio: ^4.0.6
  chart_sparkline: ^1.0.11
  #shared_preferences: ^2.0.15
  provider: ^6.0.3
  url_launcher: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf